spring.application.name=letsplay
spring.data.mongodb.uri=mongodb://mongodb:27017/letsplay
server.port=8080

jwt.secret=4bE8Lk3V9wP1mZ7cQ2rNxA6tY5uHsJ8dFgK0LpMvXnRHJhuGFHCFrtJKoiKjhTBknIOHIOvhjgHG

server.ssl.enabled=true
server.ssl.key-store=classpath:cert/letsplay.p12
server.ssl.key-store-password=letsplay2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=letsplay

admin.name=anlazaar
admin.email=anaslazaar9@gmail.com
admin.password=Admin_123